## NumPy Library

## Creation of NumPy Array

**NumPy Library :**This is a library that allows us to work with and create multi-dimensional array.

In [ ]:
# Loading the NumPy Library
import numpy as np

**Creating a NumPy Array using NumPy**

In [ ]:
# Create a List
mylist = [1,2,3,4,5]
print(mylist)

[1, 2, 3, 4, 5]


In [ ]:
# Create an Array using NumPy
np.array(mylist)

array([1, 2, 3, 4, 5])

In [ ]:
# Create an Array
np.array([6,7,8,9])

array([6, 7, 8, 9])

### Nested List to Array gets converted to Matrix 2D

In [ ]:
# Create an matrix using NumPy
mylist = [[1,2,3],[4,5,6],[7,8,9]]
print(mylist)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
# Create an Array that displays as matrix this happens for nested list
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**type() :** Used to find the datatype

In [ ]:
# To find the type
t = np.array(mylist)
type(t)

numpy.ndarray

### Creating Array using arange()

**arange() :**This In-Built Function is similar to range(start , stop , step).Displays range of Values.**This is used to create a range of array.**

In [ ]:
# Similar to range()
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Similar to range()
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Creating Array with Zeros()

In [ ]:
# Create Array with zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# Create Array with zeros 2D
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Create Array with zeros
np.zeros(5,dtype="int16")

array([0, 0, 0, 0, 0], dtype=int16)

### Creating Array using ones()

In [ ]:
# Create Array with ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# Create Array with ones 3D
np.ones((2,5,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### Create Identity Matrix

In [ ]:
# Create Identity Matrix using identity()
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Create Identity Matrix using eye()
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Linspace()

**Linspace() :** This splits the values equally in a given range **linspace(start , stop , number of numbers needed between the start and stop)**

In [ ]:
# Create the Linspace Array
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [ ]:
# Create the Linspace Array
len(np.linspace(0,5,21))

21

### Random Values

**random.rand() :**This Generates random values to an array that is a uniform distribution.

In [ ]:
# Create a random Array
np.random.rand(0,10)

array([], shape=(0, 10), dtype=float64)

In [ ]:
# Create a random Array
np.random.rand(10)

array([0.78418053, 0.32494025, 0.98485257, 0.66460099, 0.40703237,
       0.1500168 , 0.24305907, 0.96497914, 0.52899946, 0.97884302])

**random.randint() :**The randint(start , end , size).numpy. random. rand() from a uniform distribution (in the range [0,1))

In [ ]:
# Create a random Array
np.random.randint(0,20,10)

array([ 4, 10, 11,  9, 17, 17,  9,  6, 18,  0])

In [ ]:
# Create a random Array nested
np.random.randint(0,20,(2,4))

array([[10, 16,  9,  4],
       [ 0, 15,  3,  9]])

**random.randn() :** randn generates samples from the normal distribution

In [ ]:
# Create a random Array
np.random.randn(10)

array([-0.54455482, -0.55380794, -1.53881477, -1.21970006,  0.14600221,
        0.84602351,  1.69910294, -0.24987328,  0.57032963, -0.52437581])

### seed()

**seed() :**seed is a function in the NumPy library that sets the seed for generating random numbers

In [ ]:
# set the seed value
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [ ]:
# arange()
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

**reshape() :**This is to reshape the array

In [ ]:
# Reshape()
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**max() :** Finds maximum value

In [ ]:
# Maximum
arr.max()

24

**min() :**Finds minimum value

In [ ]:
# Minimum
arr.min()

0

**sum() :**Finds the total

In [ ]:
# Sum
arr.sum()

300

In [ ]:
# Create an Array
arr = np.random.randint(0,101,10)
arr

array([75, 26, 68, 23, 68, 84, 65,  7, 38, 29])

**argmax() :**This gives the index in which the maximum number is present.

In [ ]:
# find the index that has maximum value
arr.argmax()

5

**argmin() :**This gives the index in which the minimum number is present.

In [ ]:
# find the index that has minimum value
arr.argmin()

7

**dtype :**Finds the datatype

In [ ]:
# to find the datatype
arr.dtype

dtype('int64')

**shape :**It prints the number of rows and columns in an array.

In [ ]:
# shape function
arr.shape

(10,)

In [ ]:
# reshape the array
a = arr.reshape(2,5)
a

array([[75, 26, 68, 23, 68],
       [84, 65,  7, 38, 29]])

In [ ]:
# shape
a.shape

(2, 5)

# Indexing in NumPy Array

### Indexing in 1D

In [ ]:
# Create an array
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Get the element 7 from arr
arr[6]

7

**Slicing/Broadcasting Selection :**To access multiple values from the required position (start , stop) other name for this selection is called **Broadcasting Selection**

In [ ]:
# Get elements from 1 to 5 in arr
arr[1:6]

array([2, 3, 4, 5, 6])

In [ ]:
# update the first 5 numbers in the array
arr[:5] = 100

In [ ]:
# print the updated part
arr[:5]

array([100, 100, 100, 100, 100])

In [ ]:
# Print the updated array
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
# Create the array again
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Copy the array in 'a'
a = arr.copy()
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# update the 'a' array to 100
a[:] = 100

In [ ]:
# print 'a'
a

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
# Print the original array it won't be toggled
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


### Indexing in 2D

In [ ]:
# Create a 2D Array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Accessing a single element

In [ ]:
# Accessing a single element 6
arr[1,2]

6

In [ ]:
# Accessing a single element 6
arr[1][2]

6

### Accessing a Row

In [ ]:
# Access the elements from array
# Get the Row
arr[0]

array([1, 2, 3])

In [ ]:
# Access the elements from array
# Get the Row
arr[1:]

array([[4, 5, 6],
       [7, 8, 9]])

### Accessing a Column

In [ ]:
# Access the elements from array
# Get the column
arr[0:3,2]

array([3, 6, 9])

In [ ]:
# Access the elements from array
# Get the column
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
# Reshape in the arange()
array1 = np.arange(16).reshape(4,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# Accessing elements
array1[0:2, 1:3]

array([[1, 2],
       [5, 6]])

### Comparison Operation

In [ ]:
# Creating an Array
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Comparison operation for an Array
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
# Comparison operation for an Array
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
# the array of True values
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
# the array of True values alternative way
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
# Get the number of true values using len()
len(arr[arr>4])

6

#Universal Operations in NumPy Array

### Arithematic Operations

In [ ]:
# Create an Array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Addition
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# Addition
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
# subtraction
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Multiplication
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In **Division** we will get a warning in NumPy while dividing **0/0 = nan (not any number)**

In [ ]:
# division
arr / arr

<ipython-input-71-fdd55d7cf899>:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

**1/0 gives division by zero error** in python but in NumPy
on dividing 1/arr that has **1/0 will give - inf that is infinity**

In [ ]:
# division
1 / arr

<ipython-input-73-ea01b7b4f50b>:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

### universal operators

In [ ]:
# Create a 2D array
arr = np.arange(0,25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# get the sum() for the 2D array
arr.sum()

300

In [ ]:
# get the sum of the 2D Array Column-wise
arr.sum(axis=0)

array([50, 55, 60, 65, 70])

In [ ]:
# get the sum of the 2D Array Row-wise
arr.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [ ]:
# get the sin()
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

In [ ]:
# get the cos()
np.cos(arr)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722],
       [-0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462],
       [ 0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901]])

In [ ]:
# get the tan()
np.tan(arr)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01,  1.15782128e+00],
       [-3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
        -6.79971146e+00, -4.52315659e-01],
       [ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
         4.63021133e-01,  7.24460662e+00],
       [-8.55993401e-01,  3.00632242e-01,  3.49391565e+00,
        -1.13731371e+00,  1.51589471e-01],
       [ 2.23716094e+00, -1.52749853e+00,  8.85165604e-03,
         1.58815308e+00, -2.13489670e+00]])

In [ ]:
# get the log()
np.log(arr)

<ipython-input-86-1470bae28ee3>:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383]])

### Stastical Operations

In [ ]:
# get the mean for the above 2D Array
arr.mean()

12.0

In [ ]:
# get the variance
arr.var()

52.0

In [ ]:
# get the standard deviation
arr.std()

7.211102550927978